server:
  port: ${CUSTOM.SERVER.PORT:9011}

# Eureka configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
      
### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://dardan:dardan@localhost:27018/dardan?authSource=admin}

kafka:
  darwin:
    topic: darwin
    server: 127.0.0.1
    port: 9092