server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Eureka Client Config
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      circuitBreakerProduct:
        slidingWindowSize: 16
        failureRateThreshold: 75
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 200ms
        slowCallRateThreshold: 50
    instances:
      product-cb:
        base-config: circuitBreakerProduct
  timelimiter:
    configs:
      timelimiterProduct:
        timeoutDuration: 150ms
    instances:
      product-cb:
        base-config: timelimiterProduct

#filter:  
# parameters:
#   appCallerName: DarDanConfig
#   flag: true

# Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes: 
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-cb
                statusCodes: 400, 401, 403, 500, 503, 504
                fallbackUri: forward:/api/user-service/dardan/user
            # - AddRequestHeader=appCallerName, ${filter.parameters.appCallerName}
            # - AddRequestParameter=flag, ${filter.parameters.flag}
            # - name: DardanProductFilter
            #   args:
            #     headerKey: appCallerName
            #     headerValue: Java17

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
        
        - id: user-service-fallback
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/dardan/user
          filters:
            - StripPrefix=4


dardan:
  security:
    key: e564d8fc5577eef3343caee247e52430f3a9d187c5588518b67485cf36cb4fd9f354accba73019928d4fa5b678d3d90a3dc1c52be9d66e609b245341b7ca24efe0e73a4449250b0e478850b2ffa6043a00c2f51aa7826475d205da3c242313b8