server:
  port: ${CUSTOM.SERVER.PORT:9002}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://darwin:darwin@localhost:27017/darwin?authSource=admin}

### Postgresql database configuration
  jpa:
    hibernate:
      ddl-auto: update
    show: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    url: ${POSTGRESQL.URL.CONNECTION:jdbc:postgresql://localhost:5432/darwin}
    username: darwin
    password: darwin

  security:
    oauth2:
      client:
        provider:
          external:
            issuer-uri: http://localhost:8080/realms/external
        registration:
          external:
            provider: external
            client-name: external-client
            client-id: external-client
            client-secret: 3BZZCwrFdAKWxHPOdN6cTWapnLdaSMm5
            scope: openid
            authorization-grant-type: authorization_code