server:
  port: ${CUSTOM.SERVER.PORT:9001}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${CUSTOM.EUREKA.HOST:http://localhost:8761/eureka}

# MongoDB database configuration
spring:
  data:
    mongodb:
      uri: mongodb://dardan:dardan@localhost:27018/dardan?authSource=admin